name: mobile_light
description: support build fast flame mobile
version: 0.1.0+1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.16.0
  flame_forge2d: ^0.17.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
